name: Run Tests

on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -yq bison flex
          flex --version
          bison --version

      - name: Checkout Tests
        uses: actions/checkout@v2
        with:
          path: CI4C--_Compiler

      - name: Checkout Lab Codes
        uses: actions/checkout@v2
        with:
          repository: zhengzangw/C--_Compiler
          token: ${{ secrets.GITHUB_PAT }}
          path: .

      - name: Test all
        run: |
          chmod +x CI4C--_Compiler/autotest.sh
          make testall

      - name: Upload Result
        uses: actions/upload-artifact@v1
        with:
          name: result
          path: result.txt
