name: Run Tests

on: push

jobs:
  testall:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -yq bison flex
          flex --version
          bison --version
          gcc -v

      - name: Checkout Lab Codes
        uses: actions/checkout@v2
        with:
          repository: zhengzangw/C--_Compiler
          token: ${{ secrets.GITHUB_PAT }}
          submodules: true

      - name: Make irsim
        run: |
          cd irsim
          make

      - name: Test all
        run: |
          make testall | tee log.txt

      - name: Upload Log
        uses: actions/upload-artifact@v2
        with:
          name: log
          path: log.txt

  build:
    runs-on: ubuntu-16.04
    steps:
      - name: Install Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -yq bison flex
          flex --version
          bison --version
          gcc -v

      - name: Checkout Lab Codes
        uses: actions/checkout@v2
        with:
          repository: zhengzangw/C--_Compiler
          token: ${{ secrets.GITHUB_PAT }}

      - name: Build
        run: |
          make

