name: Run Tests

on: push

jobs:
  testall:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -yq bison flex
          flex --version
          bison --version

      - name: Checkout Lab Codes
        uses: actions/checkout@v2
        with:
          repository: zhengzangw/C--_Compiler
          token: ${{ secrets.GITHUB_PAT }}
          submodules: true

      - name: Make irsim
        run: |
          cd irsim
          make

      - name: Test all
        run: |
          make testall

      - name: Upload Result
        uses: actions/upload-artifact@v1
        with:
          name: result
          path: result.txt
